# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            #token_id: submit
            enabled: false

#    csrf_protection:
#        stateless_token_ids:
#            - submit
#            - authenticate
#            - logout
