framework:
  messenger:
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: 'sync://'

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: [ ]

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
      Tourze\AsyncContracts\AsyncMessageInterface: async

      # Route your messages to the transports
      # 'SymfonyTestingFramework\Message\YourMessage': async
