twig:
  file_name_pattern: '*.twig'
  default_path: '%env(TESTING_FRAMEWORK_PATH)%/templates'

when@test:
  twig:
    strict_variables: true
    default_path: '%env(TESTING_FRAMEWORK_PATH)%/templates'
