security:
  # 开发环境使用更快的密码哈希配置
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: bcrypt
      cost: 4  # 最低成本，加快开发环境的速度
    BizUserBundle\Entity\BizUser:
      algorithm: bcrypt
      cost: 4  # 最低成本，大幅提升 fixtures 加载速度
